### PR TITLE
Feature 380 phys tend plot actual

### LINKED ISSUE #380: Update fv3_physics_tend for new FV3 output format
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
Update contributed/fv3_physics_tend
Read and plot FV3 physics tendencies from new FV3 output format.  

### Time Estimate ###
*Estimate the amount of work required here.*
7 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] adapt planview_fv3.py for new formulation of no-physics (advection) tendency. Now it is reset every output just like the other tendencies. This simplifies the code. However, it can't simply be addressed in the config file.
- [x] adapt cross_section_vert.py for new nophys
- [x] adapt vert_profile_fv3.py for new nophys
- [x] add "actual" tendency panel to the multi-panel plan view plot
- [x] add --robust command line option to control colormap range to planview_fv3.py and cross_section_vert.py
- [x] fix bug in time-averaging window in planview, cross_section_vert, and vert_profile_fv3.
- [x] retain units on xarray xaxis in vert_profile_fv3.py
- [x] add vmin, vmax to planview and cross section
- [x] add xmin, xmax to vert_profile_fv3.py
- [x] clean code, leaving out unnecessary function arguments, use pep8 filter
- [x] update history file
- [x] update example plot output PNGs

### Relevant Deadlines ###
NONE
### Funding Source ###
NONE
### Assignee ###
- [x] Select **engineer**
- [x] Select **scientist**

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)** Gerard Ketefian - NOAA Affiliate <gerard.ketefian@noaa.gov> Sarah Womantree - NOAA Affiliate <sarah.womantree@noaa.gov>

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by ahijevyc**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>plot all 4 state variables (tmp, spfh, ugrd, vgrd) in all 3 scripts (planview, cross section, and vertical profile) with 1-hour time window and 2-hour time window, starting at or after initialization time. 
- [x] planview with and without vmin vmax, with all 3 types of vertical interpolation

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>Not sure how to import physics_tend.py. Is it `import physics_tend`?  or `from . import physics_tend`? pylint recommends `from .`, but this doesn't work when I test it. it has to be simpler `import physics_tend`<br>
- [ ] upload new fv3_history.nc and grid_spec.nc

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by bikegeek** [comment]
1) Under the "Recommended Testing", there is a list item to upload new fv3_history.nc and grid_spec.nc, but in the documentation, the link is pointing to the data that was put on 'mohawk' on 8/2022.  Are these new files different from the ones used in last year's development?

2) You state that pylint recommends importing like this: _from ._ rather than import physics_tend, but when using other linters, such as sonarlint (recommended for AF STIG) or ruff, this recommendation is not observed.

**Comment by bikegeek** [comment]
When running the following:
python planview_fv3.py $CONFIG $WORKING_DIR/fv3_history.nc $WORKING_DIR/grid_spec.nc tmp pbl -p 500 -t 1 -v 20190615T20 --nofineprint 

using the data downloaded by the link in the documentation, the following error is observed (is this correct?):
Traceback (most recent call last):
  File "/Volumes/d1/minnawin/feature_380_physics_tendency/METplotpy/metplotpy/contributed/fv3_physics_tend/planview_fv3.py", line 340, in <module>
    main()
  File "/Volumes/d1/minnawin/feature_380_physics_tendency/METplotpy/metplotpy/contributed/fv3_physics_tend/planview_fv3.py", line 152, in main
    assert time0 in fv3ds.time, (f"time0 {time0} not in history file. Closest is "
AssertionError: time0 2019-06-15 19:00:00 not in history file. Closest is 2019-05-04T14:00:00.000000000

or is there new input that is supposed to be used?

**Comment by ahijevyc** [comment]
New input. I wasn't sure how to upload that.

**Comment by ahijevyc** [comment]
I still have to truncate the new history file and change one of the
examples to use a time in the truncated time range.
Dave

**Comment by bikegeek** [comment]
Adding new data from the METplus Contributor's Guide (section 8.5.2):
https://metplus.readthedocs.io/en/develop/Contributors_Guide/add_use_case.html

It is pretty involved, I think that is why I did it initially for the
METplus Use Case.  Let me know if you encounter any issues with adding the
updated data.  I can try installing it when I return next Monday if you
have problems.
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Research Applications Lab
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by ahijevyc** [comment]
I logged onto DTC web server with SSH as in 8.5.2.1.
But I couldn't `runas met_test`. It asked for sudo password but ahijevyc is
not in the sudoers file.
I'll wait till you return Monday.

**Comment by bikegeek** [comment]
I am following the instructions in the updated User's Guide, and using the updated fv3_history.nc (584M) and grid_spec.nc (481K), when attempting the following:

python planview_fv3.py $CONFIG $WORKING_DIR/fv3_history.nc $WORKING_DIR/grid_spec.nc tmp pbl \
-p 500 -t 1 -v 20190615T20 --nofineprint? -p 500 -t 1 -v 20190615T20 --nofineprint

Error message:
Traceback (most recent call last):
  File "/Volumes/d1/minnawin/feature_380_physics_tendency/METplotpy/metplotpy/contributed/fv3_physics_tend/planview_fv3.py", line 340, in <module>
    main()
  File "/Volumes/d1/minnawin/feature_380_physics_tendency/METplotpy/metplotpy/contributed/fv3_physics_tend/planview_fv3.py", line 282, in main
    "projection": cartopy.crs.LambertConformal(
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/cartopy/crs.py", line 1738, in __init__
    n_parallels = len(standard_parallels)
TypeError: object of type 'NoneType' has no len()


I noticed there were some additional commits, so I made sure I had the latest changes in the branch I cloned and used for testing.  Can you reproduce these errors?

**Comment by ahijevyc** [comment]
I'll take a look.

**Comment by ahijevyc** [comment]
Hi Minna,
Thanks for trying all my new commits.

I found the culprit. cartopy changed the default params of the
LambertConformal class from `standard_parallels = None` to
`standard_parallels = (33, 45)` between 0.20.2 and 0.22.0.
I replicated the problem by updating cartopy to 0.22.0, but I fixed the
problem by removing `standard_parallels=None`.

I looked at the plot before and after the change to see if the projection
changed, and they were identical.

I committed and pushed the fixes to branch
feature_380_phys_tend_plot_actual just now.

**Comment by bikegeek** [comment]
I re-ran that same command: 
python planview_fv3.py $CONFIG $WORKING_DIR/fv3_history.nc $WORKING_DIR/grid_spec.nc tmp pbl -p 500 -t 1 -v 20190615T20 --nofineprint


and now I see this error:
Traceback (most recent call last):
  File "/Volumes/d1/minnawin/feature_380_physics_tendency/METplotpy/metplotpy/contributed/fv3_physics_tend/planview_fv3.py", line 339, in <module>
    main()
  File "/Volumes/d1/minnawin/feature_380_physics_tendency/METplotpy/metplotpy/contributed/fv3_physics_tend/planview_fv3.py", line 288, in main
    pcm = da2plot.plot.pcolormesh(x="lont", y="latt", col=col, col_wrap=ncols, robust=robust,
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/xarray/plot/accessor.py", line 802, in pcolormesh
    return dataarray_plot.pcolormesh(self._da, *args, **kwargs)
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/xarray/plot/dataarray_plot.py", line 1495, in newplotfunc
    return _easy_facetgrid(darray, kind="dataarray", **allargs)
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/xarray/plot/facetgrid.py", line 1059, in _easy_facetgrid
    return g.map_dataarray(plotfunc, x, y, **kwargs)
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/xarray/plot/facetgrid.py", line 341, in map_dataarray
    func, self.data.to_numpy(), **kwargs
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/xarray/core/dataarray.py", line 749, in to_numpy
    return self.variable.to_numpy()
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/xarray/core/variable.py", line 1298, in to_numpy
    data, *_ = chunkmanager.compute(data)
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/xarray/core/daskmanager.py", line 70, in compute
    return compute(*data, **kwargs)
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/base.py", line 599, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/core.py", line 113, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/core.py", line 113, in <listcomp>
    return [_execute_task(a, cache) for a in arg]
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/dask/utils.py", line 73, in apply
    return func(*args, **kwargs)
  File "<__array_function__ internals>", line 200, in sum
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2324, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/Volumes/d1/minnawin/miniconda3/envs/metplus_analysis_env/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: The `dtype` and `signature` arguments to ufuncs only select the general DType and not details such as the byte order or time unit. You can avoid this error by using the scalar types `np.float64` or the dtype string notation.


Do you have the version numbers of the Python packages you are using?  Here is a list of the Python packages and versions:
[current.yaml.txt](https://github.com/dtcenter/METplotpy/files/12411509/current.yaml.txt)

**Comment by ahijevyc** [comment]
I'll clone that conda environment and try it out on my end.

**Comment by ahijevyc** [comment]
I replicated the error.

I fixed it by using xarray.open_dataset instead of xarray.open_mfdataset,
but I don't like that solution because open_dataset doesn't use dask.
xarray.open_mfdataset handled the 2TB files from the NOAA folks without
running out of memory.
So I'll look for a better fix.

xarray 2022.3.0 was okay with how I handled xarray DataArrays with units
(pint quantities), but xarray 2023.5.0 is not okay.

Dave

**Comment by ahijevyc** [comment]
I couldn't fix the error, so I reverted to open_dataset from open_mfdataset
just to keep things rolling. I pushed the new code to my branch on
dtcenter/METplotpy.
Could you continue testing with this version?

**Comment by bikegeek** [comment]
The planview and vert_profile_fv3 scripts work

but it looks like there is something wrong with the cross_section_vert.py:
python cross_section_vert.py $CONFIG $WORKING_DIR/fv3_history.nc $WORKING_DIR/grid_spec.nc tmp -t 2 -v 20190615T20 -s 32 -115 -e 34 -82 --nofineprint

produces this assertion error (line 144):
assert time0 in fv3ds.time, (f"time0 {time0} not in history file. Closest is "
AssertionError: time0 2019-06-15 18:00:00 not in history file. Closest is 2019-06-15T18:03:00.000000000

When no valid time is specified, the same error is generated.  This is puzzling, since the fv3_history.nc file has 
	time:units = "hours since 2019-06-15 18:00:00" ;

**Review by bikegeek — CHANGES_REQUESTED** [review]
There are assertion errors for the cross_section_vert.py (see comment)

**Comment by ahijevyc** [comment]
I will look at cross_section_vert.py today

**Comment by ahijevyc** [comment]
The cross_section_vert.py test command should be
`python cross_section_vert.py $CONFIG $WORKING_DIR/fv3_history.nc $WORKING_DIR/grid_spec.nc ugrd -t 1 -v "2019-06-15 20" -s 28 -120 -e 26 -75 --nofineprint`
Note the -t 1 time window instead of -t 2.
-t 1.95 is another workable time window since the first time in the history file is 18:03 UTC, not 18:00 UTC.

I fixed a few matplotlib.pyplot depreciation errors in this script and two other scripts:

- axes to axs
- legendHandles to legend_handles
- plt.cm.get_cmap('cool', 2) to colormaps['cool']

working on pushing the changes...

**Comment by ahijevyc** [comment]
I pushed my changes to `feature_380_phys_tend_plot_actual` branch

**Comment by bikegeek** [comment]
Thanks, I'll update the documentation and the use case data before I merge
into develop.

**Comment by ahijevyc** [comment]
Thanks.
The feature_380_phys_tend_plot_actual branch,
 docs/Users_Guide/fv3_physics.rst documentation already has the test
commands with the "-t 1" time window. I don't think the documentation needs
to be changed.

**Review by bikegeek — APPROVED** [review]
updated tests with new data pass (all tests are being skipped due to large dataset).

**Pull request merged**
