### PR TITLE
add the error message if one of the derived components is a group #79

### LINKED ISSUE #79: Add creating derived cureves including ETB using groups
## Describe the New Feature ##
*allow creating derived curves using groups:
derived_series_1:
- - Group_y1_1 APCP_03 FAR
  - Group_y1_2 APCP_03 FAR
  - ETB
  Python doesn't support it yet.
Need to implement it
  *

### Time Estimate ###

*Issues should represent approximately 1 day of work.*

### Relevant Deadlines ###
*NONE.*

### Funding Source ###
*NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by TatianaBurek**
## Pull Request Testing ##

- [X] Describe testing already performed for these changes:
  tested with METviewer on dakota

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:
 use this XML 
[plot_20210601_153642.xml.txt](https://github.com/dtcenter/METplotpy/files/6577675/plot_20210601_153642.xml.txt)
on the dev 
http://dakota.rap.ucar.edu:8080/metviewer_dev/
The image SHOULD NOT be created and the error message should be printed:
"raise NameError("Derived curve can't be calculated."
NameError: Derived curve can't be calculated. One or both series components is a group"

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [X] Do these changes include sufficient testing updates? **[No]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by bikegeek** [comment]
Which database should I use on the 'dakota' instance of METviewer, and which plot type should I try to generate?

**Comment by TatianaBurek** [comment]
The XML for testing is in "Recommend testing" area of the PR description

**Comment by bikegeek** [comment]
I loaded that XML file and nothing happened.  It looks like it didn't
load.  I just tried again and can successfully reproduce the error.

---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Review by bikegeek — APPROVED** [review]
Successfully recreate the error message when attempting to generate a plot.

**Pull request merged**
