### PR TITLE
Feature 11 ROC diagram

### LINKED ISSUE #11: Replicate METviewer ROC diagram using Python
## Describe the New Feature ##
Plot Receiver Operating Characteristic curve using a data array including thresholds, oy_i and on_y.  Example plot, xml, and data file included

plot_20190904_141836

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###

- [x] ~2 days reverse engineer R script roc.R in the METviewer repository
- [x] ~2 days create a default config file and two custom config files (in yaml)
- [x] ~1 day implement the Config class that handles reading in the config files
- [x] ~2-3 days implement the ROC class that generates the diagram
- [x] ~1-2 days implement customization of x-ticks in Python plotly (where support exists)
- [x] Add code to generate the .html file to support interactivity in METviewer
- [X] Incorporate changes from line plot (plotly) to support formatting of x-and y-axes
- [x] ~3 days GitHub Issue #85 incorrect plot generated in METviewer 
- [x] ~3 days GitHub Issue #81 Reverse connection order
- [x] ~ 3 days Add support for event equalization (replicate behavior in roc.R_tmpl in METviewer repository)
- [x] Add pytest tests
- [x]  Update README.rst documentation

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
June 2020 for alpha
end of July 2020 for beta

### Funding Source ###
2791541

### Assignee ###
- [x] Select Minna Win and Hank Fisher
- [x] Select Tara Jensen

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] (https://github.com/NCAR/METdb/issues/new/choose), [METviewer]
- [x](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress]
- [x] (https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy]

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>
    1) Set the PYTHONPATH env variable to the following before running the command line
    commands to generate the plots:
        ${METPLOTPY_DIR}/METplotpy/metplotpy:${METPLOTPY_DIR}/METplotpy/metplotpy/plots
  
    2) Ran the following to create a plot based on default settings:
        python roc_diagram.py ./minimal_roc_diagram.yaml

        This creates a plot named _roc_diagram_default.png_

   3) Ran the following to create a plot with some customizations that will override 
   some of the settings in the roc_diagram_default.yaml config file:
        python roc_diagram.py ./custom_roc_diagram_default.yaml

       This creates a plot named _roc_diagram_actual.png_ 

- [x] Recommend testing for the reviewer to perform, including the location of input datasets:</br>
        Testing can be done within METviewer

- [x] Will this PR result in changes to the test suite? **[ No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[No]**</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [x] After submitting the PR, select **Linked Issues** with the original issue number.

### CODE REVIEW

**Comment by TatianaBurek** [comment]
Mina,
In order to proceed with testing I had to edit some of the import/from statements in roc_diagram scripts to be:
import plots.util as util
import plots.constants as constants
from plots.base_plot import BasePlot
from  plots.config import Config
from plots.series import Series

They need to be changed in the GitHub

I have problems  creating ROC with EE turned on. The results I'm getting from R and Python differ. I will let you if this is the problem in ROC or EE code after I debug this issue

**Comment by TatianaBurek** [comment]
I can't find in ROC Python this code block:
https://github.com/dtcenter/METviewer/blob/f8a9cf0ac3dc13e9e7529beb521299292c542c50/R_tmpl/roc.R_tmpl#L270
where we  add thresh_i to fix_vars for pct type. This is necessary for EE. 
Another thing that is missing - to assign indy_var='fcst_valid_beg' before calling EE:
        if self.config_obj.use_ee:
            self.parameters['indy_var'] = 'fcst_valid_beg'
            self.input_df...........
like in R:
https://github.com/dtcenter/METviewer/blob/f8a9cf0ac3dc13e9e7529beb521299292c542c50/R_tmpl/roc.R_tmpl#L302

I used #20210108_094913 for debugging

**Comment by bikegeek** [comment]
I reverted the import statements to what they were originally set for
roc_diagram.py and roc_diagram_config.py in the feature_11_ROC_diagram
feature branch.  I made changes to accommodate running from the command
line, but I will need to find another way to precisely set the command line
environment.


---------------
Minna Win
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------
Pronouns: she/her

**Comment by TatianaBurek** [comment]
The changes for the import statements work in METviewer but EE still performs incorrectly.

**Comment by bikegeek** [comment]
I didn't understand the event equalization comments before.  Now I see that
I have to add some code for event equalization.  I thought that is was
sufficient to use the METcalcpy perform_event_equalize(), which is why I
omitted the code that was originally in the R script.  I don't think I'll
have this figured out by beta3.

Thanks,
Minna
---------------
Minna Win
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------
Pronouns: she/her

**Comment by bikegeek** [comment]
Still needs more work to support event equalization and ingesting ctc or pct input

**Pull request closed without merging**
