### PR TITLE
Bugfix 218 x axis labels

### LINKED ISSUE #218: x-axis labeling doesn't follow the order specified in independent Var
## Describe the Problem ##
If indy var is not a number the order in with the values are plotted  could be incorrect.For example,
XML:
[plot_20220404_140136.xml.txt](https://github.com/dtcenter/METplotpy/files/8410352/plot_20220404_140136.xml.txt)

YAML:
```
indy_label:
- <1.0
- '>1.0'
- '>2.0'
- '>5.0'
- '>10.0'
- '>15.0'
- '>20.0'
indy_vals:
- <1.0
- '>1.0'
- '>2.0'
- '>5.0'
- '>10.0'
- '>15.0'
- '>20.0'
```
But this is the plot with incorrect x-axis order:

plot_20220404_140136

Need to fix ordering string values
### Expected Behavior ###
x-values should be plotted exactly in the same order as in YAML

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

on 'seneca', ran the new test_util.py and test_bar.py tests

create the plot using the data with threshold values and verify that the order of the x-axis labels is correct

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
re-create the bar chart using this data:
[threshold_bar.yaml.txt](https://github.com/dtcenter/METplotpy/files/11164095/threshold_bar.yaml.txt)

[threshold_bar.data.txt](https://github.com/dtcenter/METplotpy/files/11164029/threshold_bar.data.txt)

Should generate this plot:
expected_threshold

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by TatianaBurek — COMMENTED** [review]
- test_is_threshold test throws an error for values like '>.8' or  '> 3'
- other plots could have threshold values plotted on x-axis also. It would make sense to add the same logic to series (line), box, performance, contour plots

**Comment by bikegeek** [comment]
@TatianaBurek, the regular expression in the util.py and bar_series.py have been updated to include these formats.  I tested on 'seneca', and the tests are passing.  This is ready for testing on METviewer.

**Review by TatianaBurek — COMMENTED** [review]
Got errors with this plot config
[plot_20230413_174138.data.txt](https://github.com/dtcenter/METplotpy/files/11225370/plot_20230413_174138.data.txt)
[plot_20230413_174138.yaml.txt](https://github.com/dtcenter/METplotpy/files/11225372/plot_20230413_174138.yaml.txt)

**Comment by bikegeek** [comment]
Added more support for percent threshold data.  Used the data and yaml files: 
[plot_20230413_174138.data.txt](https://github.com/dtcenter/METplotpy/files/11290088/plot_20230413_174138.data.txt)

[plot_20230413_174138.yaml.txt](https://github.com/dtcenter/METplotpy/files/11290116/plot_20230413_174138.yaml.txt)

Now the plot looks like the following:

image

**Review by TatianaBurek — APPROVED** [review]
Tested with multiple databases using UI

**Pull request merged**
