### PR TITLE
Bugfix 391 fixed values

### LINKED ISSUE #391: Bugfix Inconsistency with generating plot in METviewer vs command line
*Replace italics below with details for this issue.*

## Describe the Problem ##
A NOAA visitor/intern is experiencing issues generating line/series plots via YAML configuration files.  

### Expected Behavior ###
Series plots with varying fcst_thresh values under the Fixed Values in METviewer generates expected differences in plots.  However, when setting different fcst_thresh values under the fcst_var_vals_input setting in the METplotpy YAML config file for line plot, there doesn't appear to be any differences in the resulting plots.  

METviewer is using METplotpy to generate these plots, therefore the YAML configuration files may not be set up consistently with what METviewer is sending to METplotpy.  The YAML config files that METviewer generates does not generate the fcst_var_vals_input setting values.  This makes trouble-shooting the issue challenging.

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
- on host 'seneca', using the /d1/personal/mwin/miniconda3/envs/metplus_analysis_env environment
- ran tests under METplotpy/test/line
     -  test_line_plot.py
     - test_line_groups_plot.py

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
- verify pytests pass in your own work space
- verify plotting works when using METviewer

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes ]**
- updated the custom_config.yaml file so in the User's Guide, the simpler format for setting the fixed_vars_vals_input is used

- [x] Do these changes include sufficient testing updates? **[Yes ]**
- added tests for the query logic in the utils.py (METplotpy) and for the line tests

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[At earliest convenience]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by TatianaBurek — COMMENTED** [review]
The METviewer test that include grouping, Aggegation statistic and EE failed on dakota:
```
/d3/projects/METViewer/METviewer_py3.10.4/bin/python /d3/projects/METViewer/METplotpy/metplotpy/plots/line/line.py /opt/vxwww/tomcat/webapps/metviewer_output_dev//data//plot_20231013_180341.yaml
expr cannot be an empty string
```

**Comment by TatianaBurek** [comment]
[plot_20231013_195042.data.txt](https://github.com/dtcenter/METplotpy/files/12898334/plot_20231013_195042.data.txt)
[plot_20231013_195042.yaml.txt](https://github.com/dtcenter/METplotpy/files/12898335/plot_20231013_195042.yaml.txt)

The new error message:
```
Traceback (most recent call last):
  File "/d3/projects/METViewer/METplotpy/metplotpy/plots/line/line.py", line 885, in <module>
    main()
  File "/d3/projects/METViewer/METplotpy/metplotpy/plots/line/line.py", line 874, in main
    plot = Line(docs)
  File "/d3/projects/METViewer/METplotpy/metplotpy/plots/line/line.py", line 98, in __init__
    self.series_list = self._create_series(self.input_df)
  File "/d3/projects/METViewer/METplotpy/metplotpy/plots/line/line.py", line 156, in _create_series
    series_obj = LineSeries(self.config_obj, i, input_data, series_list, name)
  File "/d3/projects/METViewer/METplotpy/metplotpy/plots/line/line_series.py", line 48, in __init__
    super().__init__(config, idx, input_data, y_axis)
  File "/d3/projects/METViewer/METplotpy/metplotpy/plots/series.py", line 72, in __init__
    self.series_points = self._create_series_points()
  File "/d3/projects/METViewer/METplotpy/metplotpy/plots/line/line_series.py", line 139, in _create_series_points
    query_string = metplotpy.plots.util.create_query(self.input_data,
  File "/d3/projects/METViewer/METplotpy/metplotpy/plots/util.py", line 387, in create_query
    logging.INFO(
TypeError: 'int' object is not callable
```

**Comment by bikegeek** [comment]
Error fixed- was calling logging when logger is not available in METplotpy's util module.

**Review by TatianaBurek — APPROVED** [review]
Manual tests with METviewer passed

**Pull request merged**
