### PR TITLE
Issue/119 box plot

### LINKED ISSUE #119: Create Box plot to be used by METviewer
*Replace italics below with details for this issue.*

## Describe the New Feature ##
*Replace box_plot.R_tmpl with the Python implementation using Plotly*

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 10 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by TatianaBurek**
## Pull Request Testing ##

- [X] Describe testing already performed for these changes:
     -  there is a test test_box.py
     -  different box plot configurations were run on dakota

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:
- test_box.py should run successfully
- try to create box plots on http://dakota.rap.ucar.edu:8080/metviewer_dev/ with different configs variables and configs (Show Notches on/off,  Points on/off ...) and compare them to the plots created by Rscript

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by TatianaBurek** [comment]
Found an issue with the Box and Line plot when the  "Reverse X Values" option is on and  "Display Number of Stats" is on.
The number of stats is not reversed. Will fix and resubmit this PR

**Comment by bikegeek** [comment]
Do you have a database that you can recommend?  I tried a few under the Testing category and haven't been able to produce a plot.  When I try to run a box plot from the command line, I get the error message:

File some object wasn’t found. (-43)

**Comment by TatianaBurek** [comment]
Here is an example:
[plot_20210622_111934.xml.txt](https://github.com/dtcenter/METplotpy/files/6696227/plot_20210622_111934.xml.txt)

And I will check the test

**Comment by bikegeek** [comment]
I didn't run the test yet, I just ran the plot from the plots/box directory.

**Comment by TatianaBurek** [comment]
On dakota:
export METPLOTPY_BASE=/d3/projects/METViewer/METplotpy/metplotpy/
export PYTHONPATH=/d3/projects/METViewer/METcalcpy:/d3/projects/METViewer/METplotpy/metplotpy
/d3/projects/METViewer/METviewer_py3.6.3//bin/python  /d3/projects/METViewer/METplotpy/metplotpy//plots/box/box.py /opt/vxwww/tomcat/webapps/metviewer_output_dev//data//plot_20210622_111934.yaml
Generates the plot

**Comment by bikegeek** [comment]
success, switching from trying to run the wrong branch to correct branch and using data from 'dakota'.

**Review by bikegeek — APPROVED** [review]
successfully generate a box plot in METviewer and from the command line on 'dakota'.  Approved

**Pull request merged**
