### PR TITLE
Feature 368 documentation for logging

### LINKED ISSUE #368: Update documentation on plots that now support logging
## Describe the Task ##
As a result of addressing the CATII and CATIII STIG issues, some METplotpy plots now have logging support.  

Update the User's Guide and necessary example config files to reflect the logging 

### Time Estimate ###
*Estimate the amount of work required here.*
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*
Before coordinated release

### Funding Source ###
2792543

### Assignee ###
- [x] Select **engineer(s)** 
- [x] Select  **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

### Verify the following:

- Verify that the default config file has the log_level set to 'info' (quotes not necessary but acceptable, case can be mixed, all upper, all lower, etc)

- Search the documentation for the following text (or mostly similar):

> In the default config file, logging is set to stdout and the log level is INFO (i.e. any log messages
> of type INFO, WARNING, and DEBUG will be logged).  If the log_filename and log_level are
> not specified in the custom configuration file, these settings will be used.

and

> To save the log output to a file, uncomment the *log_filename* entry and specify the path and
> name of the log file.  Select a directory with the appropriate read and write
> privileges.  To modify the verbosity of logging than what is set in the default config
> file, uncomment the *log_level* entry and specify the log level  (debug and info are higher verbosity, warning and error are lower verbosity).

- In the documentation where the custom config file is displayed, verify that there are log_filename and log_level in the config file

### Visually check the Users Guide in ReadtheDocs for the changes in these plots:

- bar
- box
- contour
- eclv
- ens_ss
- histogram
- histogram_2d
- hovmoeller
- line
- performance diagram
- reliability diagram
- roc_diagram
- taylor diagram
- wind rose

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
verify the same

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes ]**

- [x] Do these changes include sufficient testing updates? **[NA]** 

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by jprestop** [comment]
@bikegeek In the right hand menu, I have linked to the issue under "Development" and have added a "Status" and "Cycle" for the Project.

**Review by jprestop — COMMENTED** [review]
@bikegeek Your changes look good to me.  I have a few questions for you.

1. In this text "In the default config file, logging is set to stdout and the log level is INFO (i.e. any log messages of type INFO, WARNING, and DEBUG will be logged)." should "ERROR" be included or will log messages of type ERROR not be logged?
2. For this step "Verify that the default config file has the log_level set to 'info' (quotes not necessary but acceptable, case can be mixed, all upper, all lower, etc)", I noticed that some of the default config files were not modified for this PR and am wondering if they should be?  They are histogram_defaults.yml, scatter_defaults.yaml, taylor_diagram_defaults.yaml, and tcmpr_defaults.yaml
3. I know you gave me a list of documentation files to check, but I noticed that there are other documentation files are not referenced in this PR and I am wondering if they should be.  They are: difficulty_index.rst, s2s_blocking.rst, weather_regime.rst, spacetime.rst, make_maki_enso.rst, mjo_rmm_omi.rst, skew_t.rst, stratosphere_diagnostics.rst, polar_plot.rst, and fv3_physics.rst
4. For this step "In the documentation where the custom config file is displayed, verify that there are log_filename and log_level in the config file" 
4a. I noticed that not all of the directories under metplotpy/test had .yaml files were referenced in this PR and am wondering if they should be.  Those are: difficulty_index, equivalence_testing_bounds, fv3_physics_tend, hovmoeller, mpr_plot, series_analysis, skew_t, and spacetime_plot
4b. and that and that not all yaml files in the directories that were referenced in this PR were modified and am wondering if they should.  A subset of those are, for example, for bar: bar_with_nones.yaml, custom_defaultpoints1_bar.yaml, custom_points1_bar.yaml, minimal_bar.yaml, and threshold_bar.yaml.

**Comment by bikegeek** [comment]
@jprestop Thanks for catching the missing 'Error' in #1  I will make the addition.

for #2, I thought I committed some of the default yaml config files.  

#3 and #4 Not all the plots got the logging support incorporated.  The skew-T documentation already had information about the logging, so no changes were necessary.  

I'll let you know when I fix #1 and #2.

**Comment by bikegeek** [comment]
4a. equivalence_testing_bounds doesn't have content in the Users Guide, and was omitted.  It looks like this is some internal test.  I committed the custom_hovmoeller.yaml, somehow I didn't get that committed.  The difficulty_index, equivalence_testing_bounds, fv3_physics_tend, hovmoeller, mpr_plot, series_analysis, and spacetime_plot don't have logging support incorporated yet, and the skew_t test_skew_t.yaml in the test directory already has logging settings available in the config file (this was added when the skew-t diagram was created).  

4b.  The subset of custom config files in the test directory are not referenced in the Users Guide and as written will use the default config values for logging.  Those tests are for development/continuous integration.

**Review by jprestop — APPROVED** [review]
Looks good to me. Thanks for making the updatesl and for explaining things to me.  I approve this request.

**Pull request merged**
