### PR TITLE
Issue/181 contour

### LINKED ISSUE #181: Add the Python implementation of the Contour plot type
## Describe the New Feature ##
Implement a script that builds Contour plot similar to Rscript contour.R_tmpl.
Corresponding 
METviewer issue : https://github.com/dtcenter/METviewer/issues/363

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2700042

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by TatianaBurek**
## Pull Request Testing ##

- [X] Describe testing already performed for these changes:
- tested on dakota - example #20220131_143209
- run regression test

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:
- test on dakota  - try different configurations (reverse values, add/remove contours, use agg. stat) and compare with R
- run regression tests 

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by bikegeek — CHANGES_REQUESTED** [review]
Successfully ran tests and made modifications to the appearance of the contour plot in METviewer.  No documentation in the METplotpy read-the-docs, which will be needed for NOAA EMC staff to generate contour plots outside of the METviewer tool.

**Comment by TatianaBurek** [comment]
Minna, could you please point me to the example of the documentation in the read-the-docs to follow

**Comment by bikegeek** [comment]
I usually just copy and paste from the performance diagram rst file and
make any necessary changes:
https://github.com/dtcenter/METplotpy/blob/develop/docs/Users_Guide/performance_diagram.rst

and on read the docs:

https://metplotpy.readthedocs.io/en/develop/Users_Guide/performance_diagram.html

Lisa G has kindly reformatted a lot of the documentation so it is
consistent. I had to rewrite a lot of the documentation so the NOAA NCEP
folks could reproduce the plots in their constrained environment. Julie P
has "vetted" the correctness of the instructions on 'hera', and Logan has
verified that they work on 'orion'.  All the updated documentation made it
to the 'develop' branch.



---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by TatianaBurek** [comment]
I added documentation for the contour plot

**Review by bikegeek — APPROVED** [review]
Documentation is complete and the plot can be successfully created and modified.  Tests pass.

**Pull request merged**
