### PR TITLE
Restructure the "Conf interval" dropdown list #99

### LINKED ISSUE #99: Restructure the "Conf interval" dropdown list
## Describe the Task ##
*Reorganize "Conf interval" dropdown list. New "Conf interval" options:
std -the same
norm - rename to met_prm (MET parametric CIs). Use _ncl and _ncu columns, generated by MET. Display ONLY for if there is data for the single point - 1 data row for a point. Log a warning message otherwise - "No CIs has been displays because there is more then one data value found"
boot - the same. Consider using different column name for CIs calculated during the bootstrap to differentiate from other methods. For example, _btcl and _btcu
brier - remove
met_boot - Use _bcl and _bcu columns, generated by MET. Display ONLY for if there is data for the single point - 1 data row for a point. Log a warning message otherwise - "No CIs has been displays because there is more then one data value found"
Linked issues: 
https://github.com/dtcenter/METviewer/issues/255
https://github.com/dtcenter/METcalcpy/issues/79
*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 4h of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by TatianaBurek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:
  Run test_line+plot.py, tested using UI</br>

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

- [x] Do these changes include sufficient testing updates? **[ No]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [ ] After submitting the PR, select **Linked Issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by bikegeek — COMMENTED** [review]
line.png and line_expected.png plots have consistent content but the legend box is different (one row of labels vs 3 rows x two columns) which causes the image comparison test to fail.

**Comment by TatianaBurek** [comment]
I updated line_expected.png. The test should pass

**Review by bikegeek — APPROVED** [review]
latest update works, now all tests pass (verified via IDE and command line)

**Comment by bikegeek** [comment]
OK, I just approved it.

Thanks,
Minna
---------------
Minna Win
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------
Pronouns: she/her

**Pull request merged**
