### PR TITLE
Issue/71 equivalence testing tounds

### LINKED ISSUE #71: create Equivalence Testing Bounds plot
## Describe the New Feature ##
*Implement Equivalence Testing Bounds plot using Plotly, YAML config file and ASCII tabular input data similar to the line plot. Use line plot as an example. The plot should be used with multiple series. 
Use **ci_tost** vaues for the plot. Here is an example:
Screen Shot 2020-12-15 at 13 45 32
  *

### Acceptance Testing ###
*Users can create Equivalence Testing Bounds plot using METviewer or Python executable*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 3 days of work.*

### Relevant Deadlines ###
*NONE.*

### Funding Source ###
*NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by TatianaBurek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:
 The test for ETB plot is added to the test directory</br>

- [x] Recommend testing for the reviewer to perform, including the location of input datasets:</br>

- [x] Will this PR result in changes to the test suite? **[ No]**</br>

- [x] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[Yes]**</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [ ] After submitting the PR, select **Linked Issues** with the original issue number.

### CODE REVIEW

**Review by bikegeek — COMMENTED** [review]
The code looks good, but I encountered some issues when trying to generate a plot and running the tests:


1) I ran the test, and the last test failed:

_____________________________________________________________ test_images_match ____________________________________________________________

setup = None

    def test_images_match(setup):
        '''
            Compare an expected plot with the
            newly created plot to verify that the plot hasn't
            changed in appearance.
        '''
        path = os.getcwd()
        plot_file = './equivalence_testing_bounds.png'
        actual_file = os.path.join(path, plot_file)
        comparison = CompareImages('./equivalence_testing_bounds_expected.png', actual_file)
>       assert comparison.mssim == 1
E       assert 0.9985149916710291 == 1
E        +  where 0.9985149916710291 = <metcalcpy.compare_images.CompareImages object at 0x11fc3ccf8>.mssim

test_equivalence_testing_bounds.py:65: AssertionError
---------------------------------------------------------- Captured stdout setup ----------------------------------------------------------
WARNING: eventEqualize() detected non-unique events for ('ARWref_hrconus_control',) using [fcst_valid_beg,fcst_lead)]
WARNING: eventEqualize() detected non-unique events for ('ARWref_hrconus_experiment1',) using [fcst_valid_beg,fcst_lead)]_


2) Ran the following: 
python equivalence_testing_bounds.py ./minimal.yaml

where minimal.yaml is an empty custom config to use only defaults

Get error message about missing line.data file in the line plots directory:
FileNotFoundError: [Errno 2] File ../line/line.data does not exist: '../line/line.data'

**Comment by TatianaBurek** [comment]
Test 1 runs with success on my Mac. Is the image generating with Plotly system-dependent?
Could you do a visual testing? How different are they?
I'm not sure how do you run test 2. What is in ./minimal.yaml?

**Comment by bikegeek** [comment]
Upon visual inspection of expected vs produced plot in the tests, the up/down location of the x-axis label, "text x_label" is slightly different, but the data plotted produces the same plot.  

We still need the line.data file in the plots/line directory.

**Comment by TatianaBurek** [comment]
I added the data file

**Comment by bikegeek** [comment]
I successfully generated the plot by running equivalence_testing_bounds.py with my "custom" config file.  I caught the following changes that need to be made due to renaming of the base class in METcalcpy that transpired while you were still doing development on this task:

replace  from plots.met_plot import MetPlot
with
from plots.base_plot import BasePlot

and replace class EquivalenceTestingBounds(MetPlot):
with
class EquivalenceTestingBounds(BasePlot)

Otherwise, it looks like this is ready to merge.

**Pull request merged**
