### PR TITLE
Feature 33 cbl plot

### PR DESCRIPTION
**Pull request by bikegeek**
**Code added:**
==============
**METplotpy/metplotpy/blocking_s2s**:

- CBL_plot.py (plots the  blocking layer on a world contour plot))

- README.rst viewable in GitHub web interface

**METplotpy/test/cbl**
- test_cbl_plotting.py:  image comparison against "expected"

- README.rst - instructions on what to do prior to running test (getting data, activating conda env)

**METplotpy/test/data/cbl**
-CBL_compute.py  (used to generate the blocking layer, longitude, latitude, etc which are used to generate the plot)

- CBL_DJF_expected.png  (the expected plot from which all newly generated plots will be compared against)

- README.rst instructions on where to find input netCDF data (~87 MB, exceeds GitHub filesize limit)

### CODE REVIEW

**Comment by TatianaBurek** [comment]
Minna,
I was not able to run a test because Intellij could not find the import 
` import CBL_compute as cc`
But you code looks fine. One comment:
could you rename 
`def convert_coords(longitude):`
to something more meaningful like  convert_lon_360_to_180 or ???

**Comment by bikegeek** [comment]
Thanks for looking at this.  I'll change the name and debug the import
statement.  I hate python's packaging- I wish it was as straightforward as
Java's package system.

-Minna
---------------
Minna Win
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by TatianaBurek** [comment]
Minna,
CBL_plot.py imports convert_coords from util but the name of the method was changed to convert_lon_360_to_180:
from metcalcpy.util.utils import convert_coords

**Comment by bikegeek** [comment]
sorry, I forgot to commit everything before I logged off yesterday and I
got side-tracked with METplus training issues this morning.
I should have sent out an email before I made the pull request.  I'll let
you know when I've got everything committed and re-tested on my end
(sometime after my METplus meeting).

Thanks,
Minna
---------------
Minna Win
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by bikegeek** [comment]
still need to coordinate with the METplus driver script. Closing for now.

**Pull request closed without merging**
