### PR TITLE
Feature 294 test for nco

### LINKED ISSUE #294: Fix METplotpy tests for NCO host environment
## Describe the Problem ##
NCO is requesting a minimal amount of third-party packages which results in reducing the need for the following packages:

-    imutils
-    imageio
-    opencv-python
-    scikit-image
-    sklearn

The METplotpy tests will need to have the import for the METcalcpy CompareImages module to be commented out and the Contributor's Guide will need to document that developers who wish to run the image comparison tests will need to uncomment the import to CompareImages and comment out the pytest decorator for skipping the image comparison tests. 

In addition, pandas will be updated from version 1.2.3 to 1.5.x
Migrating from pandas 1.2.3 to pandas 1.5 may cause some 
tests to fail due to underlying changes to pandas.  Address these issues as they arise.

### Expected Behavior ###
*Provide a clear and concise description of what you expected to happen here.*

### Environment ###
Describe your runtime environment:
*1. Machine: acorn (NCO HPC development)*
*2. OS: *
*3. Software version number(s) METplotpy-2.0.0*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to METplotpy/test/<plot type>*
*2.  at command line enter 'pytest test_<plot_name>_<additional_optional_descriptor>.py*
*3. See error or failure at std out

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*
METplotpy bugfix for 2.1

### Funding Source ###
2792542, 2773542

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

- created Python 3.8 environment
- use the minimal NCO requirements for METplotpy: METplotpy/nco_requirement.txt
   -  run _pip install -r nco_requirement.txt_
- cloned the METcalcpy develop branch 
- cloned the METplotpy feature_294_test_for_nco branch
- set PYTHONPATH to $SOURCE_DIR/METcalcpy:$SOURCE_DIR/METplotpy
-   where SOURCE_DIR is the directory where you cloned the METcalcpy and METplotpy code
- cd to the $SOURCE_DIR/METplotpy/test/_plot_type_ directory and run the tests for the following plots:

- run the following command: python -m pytest test_plot_type
   - bar
   - box
   - contour
   - eclv
   - ens_ss
   - equivalence_testing_bounds
   - histogram (test_prob_hist, test_rank_hist, and test_rel_hist)
   - histogram_2d
   - line
   - mpr_plot
   - performance_diagram
   - reliability_diagram
   - revision_box
   - revision_series
   - roc_diagram
   - taylor_diagram
   - wind_rose

Verify that the tests pass without error messages about missing _imutils_ package

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
   Perform same steps as above

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]** updated the tests_github_actions.rst

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[before NCO deadline]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — CHANGES_REQUESTED** [review]
We are SO close.  Only one test failed, which was equivalence_testing_bounds/test_equivalence_testing_bounds.py:
```
============================================================================= test session starts =============================================================================
platform linux -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /apps/sw_review/emc/METplotpy/METplotpy-feature_294_test_for_nco/METplotpy/test, configfile: pytest.ini
collected 0 items / 1 error                                                                                                                                                   

=================================================================================== ERRORS ====================================================================================
_______________________________________________ ERROR collecting equivalence_testing_bounds/test_equivalence_testing_bounds.py ________________________________________________
ImportError while importing test module '/apps/sw_review/emc/METplotpy/METplotpy-feature_294_test_for_nco/METplotpy/test/equivalence_testing_bounds/test_equivalence_testing_bounds.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/apps/spack/python/3.8.6/intel/19.1.3.304/pjn2nzkjvqgmjw4hmyz43v5x4jbxjzpk/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_equivalence_testing_bounds.py:4: in <module>
    from metcalcpy.compare_images import CompareImages
../../../../../METcalcpy/METcalcpy-2.0.0/metcalcpy/compare_images.py:29: in <module>
    import imutils
E   ModuleNotFoundError: No module named 'imutils'
=========================================================================== short test summary info ===========================================================================
ERROR test_equivalence_testing_bounds.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================== 1 error in 1.65s ===============================================================================
```
I'll check "Request changes" for that fix and can retest when you're ready.  Thank you for all of your work on this. 

Also, I see this fix is in the "develop" branch.  @bikegeek, Will there be another bugfix branch for main_v2.0?

**Comment by jprestop** [comment]
@bikegeek, also, please note that I updated nco_requirements.txt, changing all of the "==" to ">=" since that is what we provided to NCO.

**Comment by bikegeek** [comment]
test for equivalence testing bounds now passes.  Forgot to comment out the import for **CompareImages**.

**Review by jprestop — APPROVED** [review]
> test for equivalence testing bounds now passes.

Thank you!  I get the same results on Acorn.  I approve this request.

**Pull request merged**
