### PR TITLE
Feature 310 python upgrade

### PR DESCRIPTION
**Pull request by bikegeek**
## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

on host 'seneca', test with nco_metplotpy.v5.1 and metplotpy.v5.1 environments

- clone feature_310_python_upgrade branch for METplotpy:

- clone the develop branch of METcalcpy   

- set the PYTHONPATH

    export METCALCPY_BASE=/path-to-source/METcalcpy
    
    export METPLOTPY_BASE=/path-to-source/METplotpy
    
    export PYTHONPATH=${METCALCPY_BASE}:${METCALCPY_BASE}/metcalcpy:${METPLOTPY_BASE}:${METPLOTPY_BASE}/metplotpy:${METPLOTPY_BASE}/metplotpy/plots

- run the tests:

   cd $METPLOTPY_BASE/test
 
   sh ./run_all_nco.sh

All tests should pass

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

   perform the same steps above, except test on host 'acorn'

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[NA]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[February 28]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Review by jprestop — CHANGES_REQUESTED** [review]
Hi @bikegeek. Unfortunately, this run isn't going as well as METdataio and METcalcpy did.  We have a few failures.  I'll paste them in below:

histogram_2d/test_histogram_2d.py
```
_______________________________________ ERROR collecting histogram_2d/test_histogram_2d.py _______________________________________
ImportError while importing test module '/apps/sw_review/emc/METplotpy/METplotpy-feature_310_python_upgrade/test/histogram_2d/test_histogram_2d.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/apps/spack/python/3.10.4/intel/19.1.3.304/xqft4d45h4dp4xnbz2ue3nbxv65i6bgp/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_histogram_2d.py:5: in <module>
    from metplotpy.plots.histogram_2d import histogram_2d as h2d
E   ModuleNotFoundError: No module named 'metplotpy'
==================================================== short test summary info =====================================================
ERROR test_histogram_2d.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================== 1 error in 0.10s ========================================================

```

test_hovmoeller.py:
```
ImportError while importing test module '/apps/sw_review/emc/METplotpy/METplotpy-feature_310_python_upgrade/test/hovmoeller/test_hovmoeller.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/apps/spack/python/3.10.4/intel/19.1.3.304/xqft4d45h4dp4xnbz2ue3nbxv65i6bgp/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_hovmoeller.py:3: in <module>
    import metplotpy.plots.hovmoeller.hovmoeller as hov
E   ModuleNotFoundError: No module named 'metplotpy'
==================================================== short test summary info =====================================================
ERROR test_hovmoeller.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================== 1 error in 0.11s ========================================================
```

test_performance_diagram.py:
```
test_performance_diagram.py F.F.s                                                                                          [100%]

============================================================ FAILURES ============================================================
____________________________________ test_plot_exists[./performance_diagram_actual.png-True] _____________________________________

setup = None, test_input = './performance_diagram_actual.png', expected_bool = True

    @pytest.mark.parametrize("test_input,expected_bool",(["./performance_diagram_actual.png", True], ["./plot_20200317_151252.points1", False]))
    def test_plot_exists(setup, test_input, expected_bool):
        '''
            Checking that only the plot file is getting created and the
             .point1 data file is not (dump_points_1 is 'False' in the test config file)
        '''
    
>       assert os.path.isfile(test_input) == expected_bool
E       AssertionError: assert False == True
E        +  where False = <function isfile at 0x14e328062170>('./performance_diagram_actual.png')
E        +    where <function isfile at 0x14e328062170> = <module 'posixpath' from '/apps/spack/python/3.10.4/intel/19.1.3.304/xqft4d45h4dp4xnbz2ue3nbxv65i6bgp/lib/python3.10/posixpath.py'>.isfile
E        +      where <module 'posixpath' from '/apps/spack/python/3.10.4/intel/19.1.3.304/xqft4d45h4dp4xnbz2ue3nbxv65i6bgp/lib/python3.10/posixpath.py'> = os.path

test_performance_diagram.py:48: AssertionError
----------------------------------------------------- Captured stdout setup ------------------------------------------------------
At least one value in the dash list must be positive
________________________________ test_files_exist[./performance_diagram_defaultpoints1.png-True] _________________________________

test_input = './performance_diagram_defaultpoints1.png', expected_bool = True

    @pytest.mark.parametrize("test_input,expected_bool",(["./performance_diagram_defaultpoints1.png", True], ["./plot_20200317_151252.points1", True]))
    def test_files_exist(test_input, expected_bool):
        '''
            Checking that only the plot file is getting created and the
             .point1 data file is not (dump_points_1 is 'False' in the test config file)
        '''
    
        os.environ['METPLOTPY_BASE'] = "../../"
        custom_config_filename = "./custom_performance_diagram_defaultpoints1.yaml"
        try:
           os.mkdir(os.path.join(os.getcwd(), 'intermed_files'))
        except FileExistsError as e:
            pass
    
        # Invoke the command to generate a Performance Diagram based on
        # the test_custom_performance_diagram.yaml custom config file.
        # Retrieve the contents of the custom config file to over-ride
        # or augment settings defined by the default config file.
        # roc.main(custom_config_filename)
        pd.main(custom_config_filename)
    
>       assert os.path.isfile(test_input) == expected_bool
E       AssertionError: assert False == True
E        +  where False = <function isfile at 0x14e328062170>('./performance_diagram_defaultpoints1.png')
E        +    where <function isfile at 0x14e328062170> = <module 'posixpath' from '/apps/spack/python/3.10.4/intel/19.1.3.304/xqft4d45h4dp4xnbz2ue3nbxv65i6bgp/lib/python3.10/posixpath.py'>.isfile
E        +      where <module 'posixpath' from '/apps/spack/python/3.10.4/intel/19.1.3.304/xqft4d45h4dp4xnbz2ue3nbxv65i6bgp/lib/python3.10/posixpath.py'> = os.path

test_performance_diagram.py:107: AssertionError
------------------------------------------------------ Captured stdout call ------------------------------------------------------
At least one value in the dash list must be positive
==================================================== short test summary info =====================================================
FAILED test_performance_diagram.py::test_plot_exists[./performance_diagram_actual.png-True] - AssertionError: assert False == True
FAILED test_performance_diagram.py::test_files_exist[./performance_diagram_defaultpoints1.png-True] - AssertionError: assert False == True
============================================= 2 failed, 2 passed, 1 skipped in 3.36s =============================================

```

revision_box/test_revision_box.py:
```
_______________________________________ ERROR collecting revision_box/test_revision_box.py _______________________________________
ImportError while importing test module '/apps/sw_review/emc/METplotpy/METplotpy-feature_310_python_upgrade/test/revision_box/test_revision_box.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/apps/spack/python/3.10.4/intel/19.1.3.304/xqft4d45h4dp4xnbz2ue3nbxv65i6bgp/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_revision_box.py:3: in <module>
    from metplotpy.plots.revision_box import revision_box
E   ModuleNotFoundError: No module named 'metplotpy'
==================================================== short test summary info =====================================================
ERROR test_revision_box.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================== 1 error in 0.10s ========================================================
```

revision_series/test_revision_series.py:
```
____________________________________ ERROR collecting revision_series/test_revision_series.py ____________________________________
ImportError while importing test module '/apps/sw_review/emc/METplotpy/METplotpy-feature_310_python_upgrade/test/revision_series/test_revision_series.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/apps/spack/python/3.10.4/intel/19.1.3.304/xqft4d45h4dp4xnbz2ue3nbxv65i6bgp/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_revision_series.py:3: in <module>
    from metplotpy.plots.revision_series import revision_series
E   ModuleNotFoundError: No module named 'metplotpy'
==================================================== short test summary info =====================================================
ERROR test_revision_series.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================== 1 error in 0.10s ========================================================
```

Please let me know if I'm doing something silly and can fix these on Acorn.  Here's what I'm running:
```
module use /apps/sw_review/emc/METcalcpy/modulefiles
module load metcalcpy/2.0.0_feature_270_python_upgrade (I named it incorrectly - it should be 2.1.0)
cd /apps/sw_review/emc/METcalcpy/METcalcpy-feature_270_python_upgrade
pip install -r nco_requirements.txt
module use /apps/sw_review/emc/METplotpy/modulefiles
module load metplotpy/2.1.0-feature_310_python_upgrade 
cd /apps/sw_review/emc/METplotpy/METplotpy-feature_310_python_upgrade
pip install -r nco_requirements.txt
cd test
./run_all_nco.sh
```

The modulefile for METcalcpy sets the environment in the following way:
```
module load intel
module load python/3.10.4

prepend-path PYTHONPATH /apps/sw_review/emc/METcalcpy/METcalcpy-feature_270_python_upgrade
```

The METplotpy modulefile sets the environment in the following way:
```
module load intel
module load python/3.10.4

setenv METPLOTPY_SOURCE /apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade
setenv METPLOTPY_BASE /apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade

prepend-path PATH /apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade/metplotpy/contributed
prepend-path PATH /apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade/metplotpy/plots/performance_diagram
prepend-path PATH /apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade/metplotpy/plots
prepend-path PATH /apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade/metplotpy
prepend-path PATH /apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade
prepend-path PYTHONPATH /apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade/metplotpy/contributed
prepend-path PYTHONPATH	/apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade/metplotpy/plots/performance_diagram
prepend-path PYTHONPATH	/apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade/metplotpy/plots
prepend-path PYTHONPATH	/apps/sw_review/emc/METplotpy/2.1.0-feature_310_python_upgrade/metplotpy
```

The base directories look like this:
```
julie.prestopnik@alogin01:/apps/sw_review/emc/METcalcpy> ls METcalcpy-feature_270_python_upgrade
docs  examples  internal  license.txt  metcalcpy  nco_requirements.txt  README.md  requirements.txt  scratch  setup.py  test

julie.prestopnik@alogin01:/apps/sw_review/emc/METplotpy> ls METplotpy-feature_310_python_upgrade 
docs  examples  internal  metplotpy  nco_requirements.txt  README.md  requirements.txt  setup.py  test
```

**Comment by bikegeek** [comment]
The errors from the performance diagram test indicate that the
modifications to performance_diagram.py aren't present.  However, upon
closer inspection, changes to the code are indeed in the version committed
to the feature_310_python_upgrade branch:

# turn on/off connecting line. 'NA' in config file turns off
# connecting line
if series.linewidth == 'NA':
linewidth = None  <-- this used to be 0, but the newer version of
Matplotlib for Python 3.10 no longer allow this.
else:
linewidth = series.linewidth


Can you verify that the change in line 290 in performance_diagram.py is in
the source code on 'acorn'?


---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Research Applications Lab
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by jprestop** [comment]
Oh @bikegeek, my apologies.  After reading your message, I realized that I had forgotten to check out the appropriate branch.  Just because the directory is named appropriately, doesn't mean that the correct branch is checked out...  I will check out the appropriate branch tomorrow and will re-run the tests.

**Review by jprestop — APPROVED** [review]
@bikegeek
Well, it turns out that once I checked out the proper branch and corrected a problem with the modulefile, all of the tests ran perfectly.  My apologies for the lack of attention to detail I had in my first round of testing.  Thank you for your guidance and patience and all of your work on this.  I approve this request.

**Comment by bikegeek** [comment]
Thanks for the update, I'm glad the other issues were also resolved.
METplotpy is a bit more complicated due to the dependencies on METcalcpy.
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Research Applications Lab
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Pull request merged**
